# -*- coding: utf-8 -*-
"""RAG using langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7sfZVNPLtb_YeyM16_n-9PmkXaibsPa

LangChain is one of the most popular frameworks for building applications with large language models (LLMs).

Key components:

1. Models - At the heart of LangChain are the models. These serve as the wrappers around LLM providers like OpenAI, Anthropic, Cohere, or Hugging Face.

2. Prompt Templates - PromptTemplate which are  reusable structures
PromptTemplate, ChatPromptTemplate, FewShotPromptTemplate

3. Chains - In LangChain, a Chain is a sequence of steps that connects components together to process input and produce output.So instead of manually calling each step, LangChain automates the pipeline.
LLMChain. LangChain Expression Language (LCEL).Sequential Chain, Router Chain(Chooses different chains based on input.)

4. Tools and Agents - Functions exposed to the agent. Examples include calculators, search tools, or database queries. it can be prebuilt or user-defined.

Decision-making LLMs that determine which tools to use and in what order.

5. Memory- Memory modules help LLMs remember previous interactions, making them ideal for conversations or tasks that require persistent context.



7. Retrieval and vector stores - Accept queries and return the most relevant documents.

Pinecone, FAISS, Chroma,

**langchain_core**

Prompt templates

Runnables (LCEL pipelines)

Message objects

Output parsers

Base LLM interfaces

**langchain_community**

vector databases

loaders

embeddings

tools

APIs
"""

!pip install langchain langchain_chroma langchain_groq pypdf langchain_community pymupdf langchain-huggingface

"""#Document Ingestion

##pypdf
"""

from langchain_community.document_loaders import PyPDFLoader

def load_pdf(file_path):
  #loader = PyMuPDFLoader(file_path) #extract page by page
  loader = PyPDFLoader(
      file_path,
      mode="single",
      #pages_delimiter="\n-------THIS IS A CUSTOM END OF PAGE-------\n",
  )  #Extract the whole PDF as a single langchain Document object
  docs= loader.load()

  return docs

documents = load_pdf("/content/GreenGrow's EcoHarvest System_ A Revolution in Farming.pdf")

for doc in documents:
    doc.page_content = doc.page_content.replace("\n", " ")

documents

"""##pymupdf"""

from langchain_community.document_loaders import PyMuPDFLoader

loader = PyMuPDFLoader("/content/GreenGrow's EcoHarvest System_ A Revolution in Farming.pdf")
documents = loader.load()  # returns list of Document objects

for doc in documents:
    doc.page_content = doc.page_content.replace("\n", " ")

documents

"""#text splitting"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    # Set a really small chunk size, just to show.
    chunk_size=1000,
    chunk_overlap=20,
    length_function=len,
    is_separator_regex=False,
)
split_docs = text_splitter.split_documents(documents)
print(f"Split {len(documents)} documents into {len(split_docs)} chunks")

split_docs

"""#generate embeddings"""

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

"""#Storing the embeddings in vector store"""

from langchain_chroma import Chroma

vector_store_chroma = Chroma.from_documents(
    split_docs,
    embedding=embeddings,
    persist_directory="./chroma_langchain_db",  # Where to save data locally, remove if not necessary
)

vector_store_chroma

"""#setup retriever"""

retriever = vector_store_chroma.as_retriever(
            search_kwargs={"k": 3}
        )

retriever.invoke('what is at the heart of the EcoHarvest System')

"""#Augmentaion

the word “augmentation” means enhancing or adding extra information to the prompt before sending it to the language model.

Adding retrieved knowledge to the prompt.
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from google.colab import userdata

model=ChatGroq(model="llama-3.3-70b-versatile", groq_api_key=userdata.get("GROQ_API_KEY"))

prompt = PromptTemplate(
    template="""
      You are an assistant for question-answering tasks.
      Use the following pieces of retrieved context to answer the question.
      If you don't know the answer, just say that you don't know.
      Use three sentences maximum and keep the answer concise.


      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

"""#creating chain

Chains allow us to combine multiple components together to create a single, coherent application.
"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(docs):
    # docs is a list of Document objects
    return "\n\n".join([doc.page_content for doc in docs])

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

parser = StrOutputParser()

main_chain = parallel_chain | prompt | model | parser

"""#Generation"""

main_chain.invoke("what is at the heart of the EcoHarvest System")